### ISSUE TITLE
how to run npm with watch and hot reload?

### ISSUE THREAD

**Issue by vesper8** [petervmeijgaard/vue-2.0-boilerplate#17]
sorry if this doesn't belong here but i thought it'd save me some time if you could just mention how to run the dev build with watch and hotreload enabled? I see you're already loading those middlewares I just don't know how to use it

thanks alot

**Comment by petervmeijgaard** [comment]
You can start the dev-server by using `npm run dev` as displayed in [README.md](https://github.com/petervmeijgaard/vue-2.0-boilerplate/blob/master/README.md#usage) under usage.
Next time read the readme before creating an issue.

**Comment by vesper8** [comment]
I did read the entire readme before I even installed this. Obviously if I'm posting here it's because I'm having trouble using the "watch" and "hot reload" as I stated. Even though I've been using  'npm run dev' all along, after editing js files and vue component files it does not automatically reload/rebuild and the only way I can see my latest changes is to ctrl-c and re-run 'npm run dev'. I would also like to use something like livereload for refreshing the browser in conjunction with file watching/rebuilding. I was asking if you could give me a hand and explain how to get this working.

If this is supposed to work out of the box because of your included middlewares then it is for some reason not working for me.

Maybe next time don't assume people who have taken upon using your wonderful contributions are morons who don't read and try to understand their problem so you can offer assistance instead?

**Comment by vesper8** [comment]
I was running npm run dev from within a virtual machine. As soon as I ran it from my mac os instead the everything began working

**Comment by skyrpex** [comment]
While I agree that Peter's answer was harsh, the original issue was pretty vague. Just my 2 cents! 💪

**Comment by petervmeijgaard** [comment]
My apologies for being harsh, but please, provide more information next time. I thought you meant that you didn't know how to start the dev server instead of having problems with it. If so, my reaction would have made perfect sense. 😉

What OS are you running inside the VM? What version of Node are you using?

**Comment by vesper8** [comment]
I'm using vagrant box 'homestead' via VirtualBox on OSX Sierra

homestead runs Ubuntu 16.04.1 LTS with everything up to date.

I can run the 'npm run dev' from my vagrant VM and then I'm able to access it by going to the http://ip:8080 (or using a .dev domain as I do by modifying my mac's hosts file)

But hot reload doesn't work that way.. it works perfect when I run it from the mac's operating system.. which is what I'll do for now.

I tried adding the watchOptions suggested in this thread http://stackoverflow.com/questions/32164246/vmware-and-webpack-hot-reload

in to the webpack.dev.conf.js file, but that didn't seem to help

When I run it from the mac, it also automatically opens up a browser tab which handles the hot-reload, but when running it from the vm it doesn't open any tab.. which might provide an hint of what's wrong

anyway I don't think this is a problem related to this project's configuration but if you have any ideas I'd still love to hear them. In the meantime running it from my mac's os is no problem at all.

**Comment by petervmeijgaard** [comment]
I don't think it's a good idea to run `npm run dev` on your VM. Homestead should in my opinion only been used to get you up and running quickly. Install the necessary software, create the databases and host the website. Running watchers and frontend stuff should been done on the host.

If you really would like to run a watcher on the VM, you can try [BrowserSync](https://www.browsersync.io/). This is an alternative to Live Reloading the boilerplate currently uses.

By the way, have you tried Laravel Valet yet? I've been using Valet instead of Homestead for some time. I simply love the simplicity and you can get a development environment up and running quickly. Still a matter of taste, but definitely worth looking into.

**Comment by petervmeijgaard** [comment]
Due to inactivity and the scope of this issue, I'll close it for now.
