### ISSUE TITLE
Structuring the files

### ISSUE THREAD

**Issue by Jordy-A** [petervmeijgaard/vue-2.0-boilerplate#21]
Hi, thanks for the great boilerplate! Question: I just started with Vue.js and I'm wondering why you're creating a new directory 'App' inside the src-directory and import the whole directory in `main.js`: (`import * as App from './app';`). I don't see a lot of other boilerplates doing the same. Is there a reason you separate `main.js`, `bootstrap.js` and `/assets/` from other app files?

Why don't you place the `<router-view>` from `Index.vue` inside `index.html` and insert store and router inside the 'new Vue()' statement and keep everything inside the src directory?

**Comment by petervmeijgaard** [comment]
Hi @Jordy-A,

Thanks for the feedback and the questions!

Doing `import * as app from './app'`, doesn't mean that I'm importing the whole directory.
I'm only importing `src/app/Index.vue`. When doing `import app from './app'`, Node will first try and look for an `app.*`-file. When it cannot find one, Node will treat `app` as a directory and will search for an `index.*`-file. Which is in this case `index.vue`. And I'm doing `import * as app from './app'` because there isn't a `default export` located in `index.vue`.

I separate these files because I don't like that the app is bloated with directories that have nothing to do with the domain logic. `bootstrap.js` is used to load all the dependencies while `main.js` is used as an entry point for Node which will require the `bootstrap.js`-file and boot the application. It will also mount the `app/index.vue`. If you want, you can combine the two, but I prefer to keep them separated.

Regaring your last question, it's okay to do that, but I prefer to use a dedicated Vue-file for this. This way you have both the JS and HTML in one single file, instead of having a bit of logic inside the `main.js`-file and the HTML-logic inside a single `index.html`-file. But it's still up to you.

Keep in mind that this is an opinionated way of structuring a Vue application. If you want to use a different structure instead, that's fine! 😄

**Comment by Jordy-A** [comment]
Great explanation, thanks! I agree, and I like the idea how you structure it :)
